import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf'; // ← IMPORT JSPDF

import '../css/log.css';

export default function Log() {
	const [users, setUsers] = useState([]);
	const [searchTerm, setSearchTerm] = useState('');
	const [sortOrder, setSortOrder] = useState('username-asc');

	useEffect(() => {
		const fetchUser = async () => {
			try {
				const res = await axios.get('http://localhost:3000/users/allusers');
				setUsers(res.data);
			} catch (err) {
				console.log('Error fetching users:', err);
			}
		};
		fetchUser();
	}, []);

	// Filter users based on search term
	const filteredUsers = users.filter(user =>
		user.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
		user.email.toLowerCase().includes(searchTerm.toLowerCase())
	);

	// Sort users based on selected criteria
	const sortedUsers = [...filteredUsers].sort((a, b) => {
		switch (sortOrder) {
			case 'username-asc':
				return a.username.localeCompare(b.username);
			case 'username-desc':
				return b.username.localeCompare(a.username);
			case 'date-newest':
				return new Date(b.createdAt) - new Date(a.createdAt);
			case 'date-oldest':
				return new Date(a.createdAt) - new Date(b.createdAt);
			default:
				return 0;
		}
	});

	// 20 user terbaru untuk PDF
	const usersForPDF = [...users]
		.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
		.slice(0, 20);

	const generateActivityLogPDF = async () => {
		if (!usersForPDF || usersForPDF.length === 0) {
			alert("No users available to print.");
			return;
		}

		const doc = new jsPDF();
		const logoImg = new Image();
		logoImg.src = '/picture/logo/logoNoBG.png';
		await new Promise((resolve, reject) => {
			logoImg.onload = resolve;
			logoImg.onerror = reject;
		});
		doc.addImage(logoImg, 'PNG', 14, 10, 30, 30);

		doc.setFont("helvetica", "bold");
		doc.setFontSize(24);
		doc.setTextColor(40, 40, 40);
		doc.text("NYX HOTEL", 50, 22);

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(100, 100, 100);
		doc.text("Luxury Accommodation & Hospitality", 50, 28);
		doc.text("123 Your Street", 50, 33);
		doc.text("City, State, Country | Tel: 555-555-1234", 50, 37);
		doc.text("info@nyxhotel.com | www.nyxhotel.com", 50, 41);

		doc.setDrawColor(193, 154, 107);
		doc.setFillColor(193, 154, 107);
		doc.rect(140, 10, 60, 12, 'F');
		doc.setTextColor(255, 255, 255);
		doc.setFont("helvetica", "bold");
		doc.setFontSize(16);
		doc.text("USER REPORT", 170, 18, { align: "center" });

		// Tambah timestamp download
		const downloadDate = new Date().toLocaleString();
		doc.setFontSize(8);
		doc.setTextColor(100, 100, 100);
		doc.text(`Generated: ${downloadDate}`, 14, 290);

		const startY = 50;
		const rowHeight = 8;
		const colWidths = [14, 70, 50, 50];
		const headers = ["No", "Username", "Email", "Created At"];

		doc.setFillColor(193, 154, 107);
		doc.rect(14, startY - 5, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
		doc.setFont("helvetica", "bold");
		doc.setFontSize(10);
		doc.setTextColor(255, 255, 255);

		let x = 14;
		headers.forEach((h, i) => {
			doc.text(h, x + 2, startY);
			x += colWidths[i];
		});

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(60, 60, 60);
		let y = startY + rowHeight;

		usersForPDF.forEach((user, index) => {
			if (index % 2 === 1) {
				doc.setFillColor(245, 245, 245);
				doc.rect(14, y - rowHeight + 2, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
			}
			x = 14;
			const row = [
				`${index + 1}`,
				user.username,
				user.email,
				new Date(user.createdAt).toLocaleString()
			];

			row.forEach((text, i) => {
				doc.text(text, x + 2, y);
				doc.setDrawColor(200, 200, 200);
				doc.rect(x, y - rowHeight + 2, colWidths[i], rowHeight);
				x += colWidths[i];
			});
			y += rowHeight;

			if (y > 280) {
				doc.addPage();
				y = 20;
			}
		});

		doc.setFontSize(8);
		doc.setTextColor(120, 120, 120);
		doc.text("Generated by Nyx Hotel Admin Dashboard", 105, 290, { align: "center" });

		const dateStr = new Date().toISOString().split('T')[0];
		doc.save(`User_Report_${dateStr}.pdf`);
	};

	return (
		<div className='w-full h-full p-6 flex flex-col'>

			{/* Search, Filter, dan Print Controls */}
			<div className='mb-4 flex gap-4'>
				<div className="relative flex-1">
					<svg className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
					</svg>
					<input
						type="text"
						placeholder="Search users..."
						value={searchTerm}
						onChange={(e) => setSearchTerm(e.target.value)}
						className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#c19a6b] focus:border-transparent"
					/>
				</div>
				
				<select
					value={sortOrder}
					onChange={(e) => setSortOrder(e.target.value)}
					className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#c19a6b] focus:border-transparent"
				>
					<option value="username-asc">Username A-Z</option>
					<option value="username-desc">Username Z-A</option>
					<option value="date-newest">Newest First</option>
					<option value="date-oldest">Oldest First</option>
				</select>

				{/* Tombol Print */}
				<button
					onClick={generateActivityLogPDF}
					className="bg-[#c19a6b] hover:bg-[#a67c52] text-white px-4 py-2 rounded-lg transition-all duration-300"
				>
					Print PDF
				</button>
			</div>

			<div className='flex-1 overflow-y-auto'>
				<div className='grid grid-cols-4 font-semibold p-3 sticky'>
					<div>No</div>
					<div>Username</div>
					<div>Email</div>
					<div>Created At</div>
				</div>

				{sortedUsers.map((user, index) => (
					<div
						key={user.id_user}
						className='grid grid-cols-4 items-center p-3'>
						<div>{index + 1}</div>
						<div>{user.username}</div>
						<div>{user.email}</div>
						<div>{new Date(user.createdAt).toLocaleString()}</div>
					</div>
				))}

				{sortedUsers.length === 0 && <div className='text-center p-4'>No users found.</div>}
			</div>
		</div>
	);
}