import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import '../css/log.css';

export default function Log() {
	const [users, setUsers] = useState([]);
	const [searchTerm, setSearchTerm] = useState('');
	const [sortOrder, setSortOrder] = useState('username-asc');

	useEffect(() => {
		fetchUser();
	}, []);

	const fetchUser = async () => {
		try {
			const res = await axios.get('http://148.230.99.149/users/allusers');
			setUsers(res.data);
		} catch (err) {
			console.log('Error fetching users:', err);
		}
	};

	const filteredUsers = users.filter(user =>
		user.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
		user.email.toLowerCase().includes(searchTerm.toLowerCase())
	);

	const sortedUsers = [...filteredUsers].sort((a, b) => {
		switch (sortOrder) {
			case 'username-asc':
				return a.username.localeCompare(b.username);
			case 'username-desc':
				return b.username.localeCompare(a.username);
			case 'date-newest':
				return new Date(b.createdAt) - new Date(a.createdAt);
			case 'date-oldest':
				return new Date(a.createdAt) - new Date(b.createdAt);
			default:
				return 0;
		}
	});

	const usersForPDF = [...users]
		.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
		.slice(0, 20);

	const generateActivityLogPDF = async () => {
		if (!usersForPDF || usersForPDF.length === 0) {
			alert("No users available to print.");
			return;
		}

		const doc = new jsPDF();
		const logoImg = new Image();
		logoImg.src = '/picture/logo/logoNoBG.png';
		await new Promise((resolve, reject) => {
			logoImg.onload = resolve;
			logoImg.onerror = reject;
		});
		doc.addImage(logoImg, 'PNG', 14, 10, 30, 30);

		doc.setFont("helvetica", "bold");
		doc.setFontSize(24);
		doc.setTextColor(40, 40, 40);
		doc.text("NYX HOTEL", 50, 22);

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(100, 100, 100);
		doc.text("Luxury Accommodation & Hospitality", 50, 28);
		doc.text("123 Your Street", 50, 33);
		doc.text("City, State, Country | Tel: 555-555-1234", 50, 37);
		doc.text("info@nyxhotel.com | www.nyxhotel.com", 50, 41);

		doc.setDrawColor(193, 154, 107);
		doc.setFillColor(193, 154, 107);
		doc.rect(140, 10, 60, 12, 'F');
		doc.setTextColor(255, 255, 255);
		doc.setFont("helvetica", "bold");
		doc.setFontSize(16);
		doc.text("USER REPORT", 170, 18, { align: "center" });

		const downloadDate = new Date().toLocaleString();
		doc.setFontSize(8);
		doc.setTextColor(100, 100, 100);
		doc.text(`Generated: ${downloadDate}`, 14, 290);

		const startY = 50;
		const rowHeight = 8;
		const colWidths = [14, 70, 50, 50];
		const headers = ["No", "Username", "Email", "Created At"];

		doc.setFillColor(193, 154, 107);
		doc.rect(14, startY - 5, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
		doc.setFont("helvetica", "bold");
		doc.setFontSize(10);
		doc.setTextColor(255, 255, 255);

		let x = 14;
		headers.forEach((h, i) => {
			doc.text(h, x + 2, startY);
			x += colWidths[i];
		});

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(60, 60, 60);
		let y = startY + rowHeight;

		usersForPDF.forEach((user, index) => {
			if (index % 2 === 1) {
				doc.setFillColor(245, 245, 245);
				doc.rect(14, y - rowHeight + 2, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
			}
			x = 14;
			const row = [
				`${index + 1}`,
				user.username,
				user.email,
				new Date(user.createdAt).toLocaleString()
			];

			row.forEach((text, i) => {
				doc.text(text, x + 2, y);
				doc.setDrawColor(200, 200, 200);
				doc.rect(x, y - rowHeight + 2, colWidths[i], rowHeight);
				x += colWidths[i];
			});
			y += rowHeight;

			if (y > 280) {
				doc.addPage();
				y = 20;
			}
		});

		doc.setFontSize(8);
		doc.setTextColor(120, 120, 120);
		doc.text("Generated by Nyx Hotel Admin Dashboard", 105, 290, { align: "center" });

		const dateStr = new Date().toISOString().split('T')[0];
		doc.save(`User_Report_${dateStr}.pdf`);
	};

	return (
		<div className='w-full h-full p-6 flex flex-col'>
			{/* Search, Filter, dan Print Controls */}
			<div className='mb-4 flex gap-4'>
				<div className="relative flex-1">
					<svg className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
					</svg>
					<input
						type="text"
						placeholder="Search users..."
						value={searchTerm}
						onChange={(e) => setSearchTerm(e.target.value)}
						className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#c19a6b] focus:border-transparent"
					/>
				</div>
				
				<select
					value={sortOrder}
					onChange={(e) => setSortOrder(e.target.value)}
					className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#c19a6b] focus:border-transparent"
				>
					<option value="username-asc">Username A-Z</option>
					<option value="username-desc">Username Z-A</option>
					<option value="date-newest">Newest First</option>
					<option value="date-oldest">Oldest First</option>
				</select>

				{/* Tombol Print */}
				<button
					onClick={generateActivityLogPDF}
					className="bg-[#c19a6b] hover:bg-[#a67c52] text-white px-4 py-2 rounded-lg transition-all duration-300"
				>
					Print PDF
				</button>
			</div>

			{/* USER LIST SECTION */}
			<div className="bg-white rounded-xl shadow-lg p-6 flex-1">
				<h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-2">
					<svg className="w-6 h-6 text-[#c19a6b]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13 0h-6" />
					</svg>
					All Users ({sortedUsers.length})
				</h2>

				<div className="overflow-y-auto" style={{ maxHeight: '400px' }}>
					<div className='grid grid-cols-4 font-semibold p-3 bg-gray-50 rounded-t-lg sticky top-0 z-10'>
						<div className="font-bold text-gray-700">No</div>
						<div className="font-bold text-gray-700">Username</div>
						<div className="font-bold text-gray-700">Email</div>
						<div className="font-bold text-gray-700">Created At</div>
					</div>

					{sortedUsers.length > 0 ? (
						sortedUsers.map((user, index) => (
							<div
								key={user.id_user}
								className={`grid grid-cols-4 items-center p-3 border-b border-gray-100 hover:bg-gray-50 transition-colors duration-150 ${
									index % 2 === 0 ? 'bg-white' : 'bg-gray-50'
								}`}
							>
								<div className="font-medium text-gray-600">{index + 1}</div>
								<div className="flex items-center gap-2">
									<span className="font-medium text-gray-900">{user.username}</span>
									{user.role === 'admin' && (
										<span className="px-2 py-0.5 text-xs bg-red-100 text-red-800 rounded-full font-bold">
											ADMIN
										</span>
									)}
								</div>
								<div className="text-gray-600 truncate" title={user.email}>{user.email}</div>
								<div className="text-gray-500 text-sm">
									{new Date(user.createdAt).toLocaleDateString('id-ID', {
										day: 'numeric',
										month: 'short',
										year: 'numeric',
										hour: '2-digit',
										minute: '2-digit'
									})}
								</div>
							</div>
						))
					) : (
						<div className='text-center p-8 text-gray-500'>
							<svg className="w-12 h-12 mx-auto text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
							</svg>
							<p className="mt-2">No users found matching your search</p>
						</div>
					)}
				</div>
			</div>
		</div>
	);
}