import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import '../css/admin.css';
import Log from '../components/log';
import RoomManagement from '../components/roomManagement';
import NavigationBar from "../components/navigationBar.jsx";
import MenuOverlay from "../components/menuOverlay.jsx";
import jsPDF from 'jspdf';

export default function Admin({ logsFromServer }) { 
	const [visibleTab, setVisibleTab] = useState(null);
	const [openMenu, setOpenMenu] = useState(false);
	const [activityLogs, setActivityLogs] = useState(logsFromServer || []);
	const navigate = useNavigate();

	const handleOpenMenu = () => setOpenMenu(true);
	const handleCloseMenu = () => setOpenMenu(false);

	const handleNavigateToSection = (section) => {
		setOpenMenu(false);
		if (!section) return;
		if (section.startsWith('/')) {
			navigate(section);
			return;
		}
		const el = document.getElementById(section);
		if (el) el.scrollIntoView({ behavior: 'smooth' });
	};

	const generateActivityLogPDF = async () => {
		if (!activityLogs || activityLogs.length === 0) {
			alert("No activity log available to print.");
			return;
		}

		const doc = new jsPDF();
		const logoImg = new Image();
		logoImg.src = '/picture/logo/logo.png';
		await new Promise((resolve, reject) => {
			logoImg.onload = resolve;
			logoImg.onerror = reject;
		});
		doc.addImage(logoImg, 'PNG', 14, 10, 30, 30);

		doc.setFont("helvetica", "bold");
		doc.setFontSize(24);
		doc.setTextColor(40, 40, 40);
		doc.text("NYX HOTEL", 50, 22);

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(100, 100, 100);
		doc.text("Luxury Accommodation & Hospitality", 50, 28);
		doc.text("123 Your Street", 50, 33);
		doc.text("City, State, Country | Tel: 555-555-1234", 50, 37);
		doc.text("info@nyxhotel.com | www.nyxhotel.com", 50, 41);

		doc.setDrawColor(193, 154, 107);
		doc.setFillColor(193, 154, 107);
		doc.rect(140, 10, 60, 12, 'F');
		doc.setTextColor(255, 255, 255);
		doc.setFont("helvetica", "bold");
		doc.setFontSize(16);
		doc.text("ACTIVITY LOG", 170, 18, { align: "center" });

		const startY = 50;
		const rowHeight = 8;
		const colWidths = [14, 70, 50, 50];
		const headers = ["No", "Username", "Email", "Created Data"];

		doc.setFillColor(193, 154, 107);
		doc.rect(14, startY - 5, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
		doc.setFont("helvetica", "bold");
		doc.setFontSize(10);
		doc.setTextColor(255, 255, 255);

		let x = 14;
		headers.forEach((h, i) => {
			doc.text(h, x + 2, startY);
			x += colWidths[i];
		});

		doc.setFont("helvetica", "normal");
		doc.setFontSize(9);
		doc.setTextColor(60, 60, 60);
		let y = startY + rowHeight;

		activityLogs.forEach((log, index) => {
			if (index % 2 === 1) {
				doc.setFillColor(245, 245, 245);
				doc.rect(14, y - rowHeight + 2, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
			}
			x = 14;
			const row = [
				`${index + 1}`,
				log.username,
				new Date(log.loginTime).toLocaleString(),
				log.ip || "-"
			];

			row.forEach((text, i) => {
				doc.text(text, x + 2, y);
				doc.setDrawColor(200, 200, 200);
				doc.rect(x, y - rowHeight + 2, colWidths[i], rowHeight);
				x += colWidths[i];
			});
			y += rowHeight;

			if (y > 280) {
				doc.addPage();
				y = 20;
			}
		});

		doc.setFontSize(8);
		doc.setTextColor(120, 120, 120);
		doc.text("Generated by Nyx Hotel Admin Dashboard", 105, 290, { align: "center" });

		doc.save("Activity_Log.pdf");
	};

	const currentTab = () => {
		switch (visibleTab) {
			case 'log':
				return (
					<div className="flex flex-col relative">
						<Log logs={activityLogs} />
						<button
							onClick={generateActivityLogPDF}
							className="print-btn fixed-print-btn"
						>
							Print PDF
						</button>
					</div>
				);
			case 'room':
				return <RoomManagement />;
			default:
				return (
					<div className="admin-placeholder">
						<div className="text-center py-12">
							<div className="w-24 h-24 bg-[#102E50] rounded-full flex items-center justify-center mx-auto mb-4">
								<img src="/picture/logo/logoNoBG.png" alt="Logo" className="w-22 h-22" />
							</div>
							<h2 className="text-2xl font-bold text-gray-800 mb-2">Welcome to Admin Dashboard</h2>
							<p className="text-gray-600 max-w-md mx-auto">
								Select a section from the sidebar to manage your hotel operations.
							</p>
						</div>
					</div>
				);
		}
	};

	return (
		<div className='admin-container'>
			<NavigationBar openMenu={openMenu} handleOpenMenu={handleOpenMenu} />
			<MenuOverlay
				isOpen={openMenu}
				onClose={handleCloseMenu}
				onNavigate={handleNavigateToSection}
			/>

			<div className='w-full h-17 fixed flex items-center justify-between px-8 py-2 bg-[#102E50] text-white z-10 shadow-md'>
				<h1 className='text-xl font-semibold tracking-wide'>Admin Dashboard</h1>
				<Link to='/login'>
					<button className='logout-btn'>Log Out</button>
				</Link>
			</div>

			<div className="admin-main pt-20 flex">
				<aside className="admin-sidebar">
					<button
						onClick={() => setVisibleTab('room')}
						className={`sidebar-btn ${visibleTab === 'room' ? 'active' : ''}`}
					>
						Room Management
					</button>
					<button
						onClick={() => setVisibleTab('log')}
						className={`sidebar-btn ${visibleTab === 'log' ? 'active' : ''}`}
					>
						Activity Log
					</button>
				</aside>

				<main className='admin-content flex-1'>
					<div className='content-card'>{currentTab()}</div>
				</main>
			</div>
		</div>
	);
}
